/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function pino(options?: object | undefined | null): Logger
export declare class Logger {
  constructor(options?: object | undefined | null)
  trace(msgOrObj: string | object, msg?: string | undefined | null): void
  debug(msgOrObj: string | object, msg?: string | undefined | null): void
  info(msgOrObj: string | object, msg?: string | undefined | null): void
  warn(msgOrObj: string | object, msg?: string | undefined | null): void
  error(msgOrObj: string | object, msg?: string | undefined | null): void
  fatal(msgOrObj: string | object, msg?: string | undefined | null): void
  child(bindings: object): Logger
  bindings(): object
}
