/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'pino-rs.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./pino-rs.android-arm64.node')
          } else {
            nativeBinding = require('pino-rs-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'pino-rs.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./pino-rs.android-arm-eabi.node')
          } else {
            nativeBinding = require('pino-rs-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'pino-rs.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./pino-rs.win32-x64-msvc.node')
          } else {
            nativeBinding = require('pino-rs-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'pino-rs.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./pino-rs.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('pino-rs-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'pino-rs.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./pino-rs.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('pino-rs-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'pino-rs.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./pino-rs.darwin-universal.node')
      } else {
        nativeBinding = require('pino-rs-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'pino-rs.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./pino-rs.darwin-x64.node')
          } else {
            nativeBinding = require('pino-rs-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'pino-rs.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./pino-rs.darwin-arm64.node')
          } else {
            nativeBinding = require('pino-rs-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'pino-rs.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./pino-rs.freebsd-x64.node')
      } else {
        nativeBinding = require('pino-rs-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'pino-rs.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./pino-rs.linux-x64-musl.node')
            } else {
              nativeBinding = require('pino-rs-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'pino-rs.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./pino-rs.linux-x64-gnu.node')
            } else {
              nativeBinding = require('pino-rs-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'pino-rs.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./pino-rs.linux-arm64-musl.node')
            } else {
              nativeBinding = require('pino-rs-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'pino-rs.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./pino-rs.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('pino-rs-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'pino-rs.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./pino-rs.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('pino-rs-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'pino-rs.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./pino-rs.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('pino-rs-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'pino-rs.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./pino-rs.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('pino-rs-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'pino-rs.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./pino-rs.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('pino-rs-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'pino-rs.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./pino-rs.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('pino-rs-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { Logger, pino } = nativeBinding

// Standard time functions (pino.js compatibility)
const stdTimeFunctions = {
  epochTime: () => `,"time":${Date.now()}`,
  unixTime: () => `,"time":${Math.round(Date.now() / 1000)}`,
  isoTime: () => `,"time":"${new Date().toISOString()}"`,
  nullTime: () => ''
}

// Standard serializers (pino.js compatibility)
const stdSerializers = {
  req: (req) => ({
    method: req.method,
    url: req.url,
    headers: req.headers,
    remoteAddress: req.socket?.remoteAddress,
    remotePort: req.socket?.remotePort
  }),
  res: (res) => ({
    statusCode: res.statusCode,
    headers: res.getHeaders ? res.getHeaders() : {}
  }),
  err: (err) => ({
    type: err.constructor?.name || 'Error',
    message: err.message,
    stack: err.stack,
    ...(err.code && { code: err.code })
  })
}

// Log levels
const levels = {
  values: {
    fatal: 60,
    error: 50,
    warn: 40,
    info: 30,
    debug: 20,
    trace: 10
  },
  labels: {
    10: 'trace',
    20: 'debug',
    30: 'info',
    40: 'warn',
    50: 'error',
    60: 'fatal'
  }
}

module.exports = pino
module.exports.pino = pino
module.exports.Logger = Logger
module.exports.default = pino
module.exports.stdTimeFunctions = stdTimeFunctions
module.exports.stdSerializers = stdSerializers
module.exports.levels = levels

